name: Publish to the Maven Central Repository
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Maven Central Repository
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
      - name: Check version
        run: |
          TAIL=$(./mvnw --non-recursive help:evaluate -Dexpression=project.version -q -DforceStdout | awk '{ sub(".*-",""); printf $0; }')"
          echo "TAIL=${TAIL}" >> $GITHUB_ENV
      - name: SNAPSHOT
        if: env.TAIL == 'SNAPSHOT'
        run: mvn deploy --batch-mode --also-make --projects bootiful-sqltemplate
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
      - name: RELEASE
        if: steps.SNAPSHOT.conclusion == 'skipped'
        run: mvn deploy --batch-mode --activate-profiles release --also-make --projects bootiful-sqltemplate
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
